GET http://localhost:3001/api/notes/
### 
GET http://localhost:3001/api/notes/5f562f449617fb50dfee1435
### 
DELETE http://localhost:3001/api/notes/5f562f449617fb50dfee1435
###
POST http://localhost:3001/api/notes/
Content-Type: application/json

{
    "content":"2",
    "important":false
}

### 
PUT  http://localhost:3001/api/notes/5f61bb68ce5e383639985c1d
